# Generated by Django 4.2 on 2023-04-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cars_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cost_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=42, verbose_name='Per Day Rate'),
        ),
        migrations.AddField(
            model_name='car',
            name='cost_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=42, verbose_name='Cost Hour'),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Petrol'), (2, 'Diesel')], default=1, verbose_name='Fuel'),
        ),
        migrations.AddField(
            model_name='car',
            name='leasing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=42, verbose_name='Leasing'),
        ),
        migrations.AddField(
            model_name='car',
            name='luggage',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Luggage'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Mileage'),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Seats'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manual'), (2, 'Automat')], default=1, verbose_name='Transmission'),
        ),
    ]
