# Generated by Django 4.2 on 2023-04-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_car_cost_day_car_cost_hour_car_description_car_fuel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_type', models.PositiveSmallIntegerField(choices=[(1, 'Per Hour Rate'), (2, 'Per Day Rate'), (2, 'Leasing')], default=1, verbose_name='Transmission')),
                ('pick_up_location', models.CharField(blank=True, max_length=128, null=True, verbose_name='Pick-Up Location')),
                ('drop_off_location', models.CharField(blank=True, max_length=128, null=True, verbose_name='Drop-Off Location')),
                ('pick_up_date', models.DateTimeField(auto_now_add=True, verbose_name='Pick_Up Date')),
                ('drop_off_date', models.DateTimeField(auto_now=True, verbose_name='Drop-Off Date')),
                ('pick_up_time', models.CharField(blank=True, max_length=128, null=True, verbose_name='Pick-Up Time')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_issue', to='core.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Rent Issue',
                'verbose_name_plural': 'Rent Issues',
            },
        ),
    ]
