# Generated by Django 4.2 on 2023-04-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rentissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentissue',
            name='drop_off_date',
            field=models.DateTimeField(verbose_name='Drop-Off Date'),
        ),
        migrations.AlterField(
            model_name='rentissue',
            name='pick_up_date',
            field=models.DateTimeField(verbose_name='Pick_Up Date'),
        ),
        migrations.AlterField(
            model_name='rentissue',
            name='rent_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Per Hour Rate'), (2, 'Per Day Rate'), (2, 'Leasing')], default=1, verbose_name='Rent Type'),
        ),
    ]
