# Generated by Django 4.2 on 2023-04-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usermessage_alter_rentissue_rent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Car Comment',
                'verbose_name_plural': 'Car Comments',
            },
        ),
    ]
