# Generated by Django 4.2 on 2023-04-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_carcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcomment',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created at'),
        ),
    ]
