# Generated by Django 4.2 on 2023-04-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_carcomment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
